import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { GlassNavbar } from "@/components/navbar";

// Configure Roboto font
const roboto = Roboto({
  weight: ["400", "500", "700"], // Regular, Medium, and Bold weights
  variable: "--font-roboto",     // CSS variable to pass to Tailwind
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <GlassNavbar />
        {children}
      </body>
    </html>
  );
}