import type { Metadata } from "next";
import { GlassNavbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "PulseFit",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <GlassNavbar />
      {children}
    </>
  );
}